name: python.yml
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - run: |
          pip install -e ./tools[test]

      - run: |
          mypy ./tools/src 
          black --check ./tools
          pytest ./tools/tests/*
